cfg_bagWeights = {}

cfg_bagWeights.RequiredBagComponent = 5

cfg_bagWeights.Bags = {
    [226] = 20.0,
    [215] = 5.0,
    [210] = 18.0,
    [187] = 15.0,
    [186] = 20.0,
    [185] = 20.0,
    [184] = 7.0,
    [183] = 17.0,
    [182] = 15.0,
    [134] = 20.0,
    [133] = 18.0,
    [86] = 15.0,
    [85] = 10.0,
    [82] = 20.0,
    [81] = 15.0,
    [46] = 20.0,
    [45] = 20.0,
    [184] = 20.0,
    [44] = 12.0,
    [41] = 20.0,
    [40] = 15.0,
    [0] = 0.0
}

cfg_bagWeights.HeavyWeapons = {
    "WEAPON_ASSAULTRIFLE",
    "WEAPON_ASSAULTRIFLE_MK2",
    "WEAPON_CARBINERIFLE",
    "WEAPON_CARBINERIFLE_MK2",
    "WEAPON_ADVANCEDRIFLE",
    "WEAPON_SPECIALCARBINE",
    "WEAPON_SPECIALCARBINE_MK2",
    "WEAPON_BULLPUPRIFLE",
    "WEAPON_BULLPUPRIFLE_MK2",
    "WEAPON_COMPACTRIFLE",
    "WEAPON_MILITARYRIFLE",
    "WEAPON_HEAVYRIFLE",
    "WEAPON_TACTICALRIFLE",
    "WEAPON_MG",
    "WEAPON_COMBATMG",
    "WEAPON_COMBATMG_MK2",
    "WEAPON_GUSENBERG",
    "WEAPON_HK416B",
    "WEAPON_MK18B",
    "WEAPON_SCAR17",
    "WEAPON_AQAK",
    "WEAPON_REDL",
    "WEAPON_FAMAS",
    "WEAPON_PUMPKIN",
    "WEAPON_XMASRIFLE",
    "WEAPON_ASSAULTRIFLELS",
    "WEAPON_M4LOVER",
    "WEAPON_KS1",
    "WEAPON_SLICE",
    "WEAPON_HATMAS",
    "WEAPON_SANTAS",
    "WEAPON_PBLACKVAL",
    "WEAPON_CARROTTEC",
    "WEAPON_M415",
    "WEAPON_AK_SHORTSTOCK_CHR",
    "WEAPON_SCAR-L",
    "WEAPON_CZ_SCORPION_EVO_CHR",
    "WEAPON_MLTM4R_CHR",
    "WEAPON_NVRIFLE_CHR",
    "WEAPON_TR_88_CHR",
    "WEAPON_M4BEAST",
    "WEAPON_TAR21",
    "WEAPON_CHAINSAW",
    "WEAPON_A15RC",
    "WEAPON_L85_CHR",
    "WEAPON_GK47",
    "WEAPON_R90_CHR",
    "WEAPON_G3_2",
    "WEAPON_AUG",
    "WEAPON_M16A1_CHR",
    "WEAPON_HX_15_CHR",
    "WEAPON_VX_47_CHR",
    "WEAPON_G36",
    "WEAPON_G3_2",
    "WEAPON_GALILARV2",
    "WEAPON_SR_3M_CHR",
    "WEAPON_GROZA",
    "WEAPON_SACR_L_CHR",
}